/**
 * Lexicon and compiled patterns for the rule-based costume-cue extractor (scriptCues.ts).
 * Everything here is built once at module load from scriptCuesVocab.ts.
 */
import { VOCAB, NOT_GARMENT_CONTEXTS } from "./scriptCuesVocab";

export const uniq = <T>(a: T[]): T[] => Array.from(new Set(a));
export const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
export const alt = (words: string[]) => uniq(words).sort((a, b) => b.length - a.length).map((w) => esc(w).replace(/[- ]/g, "[- ]")).join("|");
export const cap = (s: string) => s.charAt(0).toUpperCase() + s.slice(1);
export const title = (s: string) => s.toLowerCase().replace(/(^|[\s-]|'(?!s\b))([a-z])/g, (_m, p: string, c: string) => p + c.toUpperCase());
export const B0 = "(?<![A-Za-z-])";
export const B1 = "(?![A-Za-z-])";

// ---------- heads (garments, accessories, footwear) ----------
const HEADS = [...VOCAB.garments, ...VOCAB.accessories, ...VOCAB.footwear];
const GARMENT_SET = new Set(VOCAB.garments);
const CANON = new Map(HEADS.map((w) => [w.replace(/[- ]/g, ""), w]));
export const canon = (w: string) => CANON.get(w.toLowerCase().replace(/[- ]/g, "")) || w.toLowerCase();
export const kindOfHead = (c: string): "GARMENT" | "ACCESSORY" => (GARMENT_SET.has(c) ? "GARMENT" : "ACCESSORY");
export const HEAD_ALT = alt(HEADS);
export const HEAD_RE = new RegExp(`${B0}(${HEAD_ALT})(es|s)?${B1}`, "gi");
/** Heads that are usually verbs or non-costume nouns unless a determiner/modifier makes them concrete. */
export const AMBIG = new Set(["watch", "ring", "tie", "chain", "cap", "belt", "top", "bag", "slip", "wrap", "boot", "vest", "mask", "brace", "heel", "flat", "pump", "clutch", "case", "tank", "cross", "kit", "habit", "cut", "sling", "cast", "platform", "wedge", "hood", "cane", "cleat", "net", "mala", "kara", "haar", "trunks", "specs", "shades", "cover", "coat", "purse", "pocket", "collar", "cuff", "band", "pin", "stud", "hat", "suit", "robe", "medal", "sock", "cape", "veil", "crown", "glove", "train", "tights", "jersey", "dress", "clothes", "clothing", "shawl", "double"]);
/** Ambiguous heads whose non-costume sense is at least as common ("the flat", "the ring", "the top", "the cast"): with only a bare
 * determiner they need an explicit wearing verb, a body-part tail or a modifier/possessive before they count. */
export const STRONG_AMBIG = new Set(["watch", "ring", "tie", "chain", "cap", "top", "bag", "slip", "wrap", "boot", "mask", "brace", "heel", "flat", "pump", "clutch", "case", "tank", "cross", "kit", "habit", "cut", "sling", "cast", "platform", "wedge", "hood", "cleat", "net", "trunks", "specs", "shades", "cover", "pocket", "collar", "cuff", "band", "pin", "stud", "train", "double", "mala", "haar", "kara"]);
/** Footwear that comes in pairs: the singular is almost always the non-shoe sense ("the flat", "his heel", "the platform"). */
export const PAIR_ONLY = new Set(["flat", "platform", "wedge", "pump", "cleat", "heel"]);
/** Strong-ambiguous heads that are still plausible when dropped or handed over. */
export const JEWEL_LIKE = new Set(["ring", "watch", "chain", "tie", "bag", "mask", "cap"]);
/** Heads that are containers when something is put "into" them. */
export const CONTAINER = new Set(["suitcase", "briefcase", "duffel", "backpack", "rucksack", "satchel", "tote", "handbag", "bag", "purse", "potli", "wallet", "pocket", "case"]);
export const BARE_FEET = /\b(barefoot|bare feet|bare-footed|shoeless|stockinged feet)\b/i;

// ---------- modifiers (colours, materials, conditions) ----------
const MODS = uniq([...VOCAB.colours, ...VOCAB.materials, ...VOCAB.conditions]);
export const MOD_ALT = alt(MODS);
export const MOD_TAIL_RE = new RegExp(`(?:^|[\\s,])(${MOD_ALT}|[a-z]+-[a-z]+)\\s*,?\\s*$`, "i");
/** Last lower-case word before the head (candidate unknown adjective such as "aviator", "evening", "cocktail"). */
export const UNKNOWN_ADJ_RE = /(?:^|\s)([a-z]{3,}(?:'s)?)\s*,?\s*$/;
/** What may precede an unknown adjective for it to count as part of the phrase: a determiner, another modifier, "and" or a comma. */
export const ADJ_LEAD_RE = new RegExp(`(?:^|\\s)(?:a|an|the|his|her|their|my|your|its|and|,|${MOD_ALT}|[a-z]+-[a-z]+)\\s*,?\\s*$`, "i");
/** Adverbs/intensifiers that may sit inside a modifier chain without breaking it ("heavily starched", "very long"). */
export const ADV_SKIP = new Set(["very", "quite", "rather", "slightly", "somewhat", "extremely", "deeply", "heavily", "immaculately", "brilliantly", "finely", "beautifully", "perfectly", "badly", "neatly", "impeccably", "elegantly", "richly", "lightly", "faintly", "freshly", "newly", "sharply", "smartly", "too", "so", "really", "fairly", "pretty"]);
/** -ing / -ed words that are garment descriptors rather than verbs. */
export const KNOWN_ING = new Set(["wedding", "evening", "morning", "running", "riding", "sleeping", "walking", "hiking", "boxing", "wrestling", "shooting", "hunting", "training", "swimming", "bathing", "dancing", "cycling", "jogging", "fishing", "sailing", "climbing", "dining", "smoking", "gardening", "nursing", "fencing", "racing", "sporting", "bowling", "skiing", "mourning", "christening", "wedding-day", "bridal", "flowing", "billowing", "clinging", "matching", "fitted", "tailored", "pleated", "printed", "embroidered", "sequinned", "sequined", "beaded", "quilted", "padded", "lined", "ribbed", "belted", "buttoned", "zipped", "hooded", "collared", "cropped", "distressed", "ripped", "faded", "frayed", "patched", "striped", "checked", "checkered", "dotted", "layered", "ruffled", "frilled", "tiered", "tapered", "flared", "cuffed", "rolled", "starched", "pressed", "ironed", "washed", "unwashed", "unironed", "creased", "crumpled", "peaked", "pointed", "brimmed", "wide-brimmed", "studded", "spiked", "feathered", "tasselled", "tasseled", "fringed", "knotted", "mirrored", "tinted", "polarised", "polarized", "strapped", "buckled", "bejewelled", "jewelled", "gilded", "plumed", "waxed", "oiled", "polished", "scuffed", "crested", "monogrammed", "branded", "laced", "gloved", "cuffed", "capped"]);
export const ADJ_STOP = new Set("and or but the a an in on at with of to for from by is are was were has have had his her their its my your not no then than that this these those who which as like into onto over under up down off out still now also both all some any one two three four five six ten twenty fifty hundred wears wearing wear puts pulls takes kicks throws peels slips checks twists pushes loosens tightens adjusts straightens holds holding carries carrying clutching walks with sits stands arrives waits looks turns runs steps same identical usual other another each every only just even more most less last next first second whole entire top bottom left right front back same".split(" "));
export const DET_RE = /(?:^|\s)(a pair of|a set of|a|an|the|his|her|their|my|your|its|full|yesterday's|matching|some|that|those|these|another)\s*$/i;
const COND_SET = new Set(VOCAB.conditions);
/** Condition words that do not describe damage or disarray (no CONDITION cue when used as a modifier). */
const BENIGN = new Set(["new", "old", "fresh", "crisp", "clean", "plain", "simple", "pristine", "spotless", "immaculate", "pressed", "ironed", "starched", "open", "loose", "tight", "cut", "worn", "caught", "stuck", "twisted", "baggy", "fitted", "brand-new", "hooded", "matching", "light", "dark", "pale", "bright", "school", "riot", "police", "army", "military", "hospital", "wet-look"]);
export const isCondMod = (w: string) => COND_SET.has(w) && !BENIGN.has(w);
export const COND_ALT = alt(VOCAB.conditions.filter((c) => !BENIGN.has(c)));
/** Sticky predicate after a noun phrase: "is soaked and torn", "now soaked through", "is still blood-stained". */
export const PRED_RE = new RegExp(`((?:\\s+(?:is|are|was|were|now|still|already|completely|half|hangs|clings|looks|and))*)\\s+(${COND_ALT})(\\s+through)?((?:(?:\\s+and\\s+|,\\s*)(?:${COND_ALT}))*)${B1}`, "iy");
/** Condition words that stand on their own as a predicate or appositive ("Raj is soaked", "Priya, dripping wet, glares"). */
const BARE_CONDS = ["soaked to the skin", "soaking wet", "dripping wet", "wet through", "soaked through", "soaked", "drenched", "dripping", "sodden", "sopping", "sopping wet", "damp", "dishevelled", "disheveled", "bedraggled", "muddy", "mud-spattered", "mud-splattered", "mud-caked", "caked in mud", "covered in mud", "filthy", "dusty", "dust-covered", "bloodied", "blood-soaked", "blood-stained", "bloodstained", "covered in blood", "sweaty", "sweat-soaked", "sweat-stained", "singed", "charred", "scorched", "burnt", "unkempt", "crumpled", "rumpled", "wet", "gulal-smeared", "haldi-stained", "turmeric-stained", "colour-stained", "paint-splattered", "grimy", "sooty", "soot-covered", "snow-covered", "frozen", "half-dressed", "hastily dressed", "dirty", "tattered", "ragged", "in rags"];
export const BARE_COND_ALT = alt(BARE_CONDS);
export const BARE_COND_RE = new RegExp(`(?:^|[,;(]\\s*|\\b(?:is|are|was|were|looks?|looking|stands|sits|arrives|enters|returns|emerges|comes in|comes back|both|all|everyone|and|but)\\s+)(?:(?:now|still|completely|absolutely|utterly|totally|already|visibly|thoroughly|slightly|half)\\s+)?(${BARE_COND_ALT})(?=[,.;!?)]|\\s+(?:from|through|to the|and|but|with|after|by|in|as|head to toe)\\b|$)`, "gi");
export const FIT_RE = /^\s*(?:(?:is|are|looks?|hangs)\s+)?(two sizes too (?:big|small)|a size too (?:big|small)|too (?:big|small|tight|loose|short|long)|ill-fitting)\b/i;
export const IDIOM_RE = /\b(sleeves rolled(?: up)?|top button (?:open|undone)|shirt (?:untucked|unbuttoned|open)|collar (?:up|turned up|loosened|open)|tie loosened|hood up|buttons? missing|hair wet)\b/gi;

// ---------- anti-patterns ----------
export const NOT_RE = new RegExp(NOT_GARMENT_CONTEXTS.map((x) => `(?:${x})`).join("|"), "gi");
export type Span = [number, number];
export function blockedSpans(s: string): Span[] {
  const spans: Span[] = []; NOT_RE.lastIndex = 0; let m: RegExpExecArray | null;
  while ((m = NOT_RE.exec(s))) {
    if (!m[0]) { NOT_RE.lastIndex++; continue; }
    spans.push([m.index, /^(like a|as if|as though)$/i.test(m[0]) ? s.length : m.index + m[0].length]);
  }
  return spans;
}
export const overlaps = (spans: Span[], a: number, b: number) => spans.some(([x, y]) => a < y && b > x);
export const DEPICT_RE = /\b(photo|photograph|picture|poster|portrait|painting|billboard|magazine|mannequin|dummy|statue|screen|television|TV|hoarding)\b/i;
export const IMAGINE_RE = /\b(imagines|pictures (?:himself|herself|him|her|them)|dreams? (?:of|about)|would look|could wear|might wear|wishes|fantasises|fantasizes|remembers|recalls|thinks (?:of|about|back to)|visualises|visualizes|misses|imagined|remembered|daydreams? (?:of|about)|reminisces)\b/i;
/** Object-like token after a head means the head is a verb ("watches the door", "tops up", "pockets his phone"). */
export const VERB_AFTER_RE = /^\s+(?:the|a|an|his|her|their|him|them|it|me|us|up|down|off|out|at|for|from|into|onto|over|around|through|away|back)\b/i;
export const SUBJ_PRONOUN_BEFORE_RE = /\b(?:he|she|they|it|who|then)\s*$/i;
/** Words that may follow an ambiguous head without turning it into a modifier ("the top shelf" fails, "the top button" passes as a head-of-head). */
const AFTER_OK = new Set("and or but as in on at with of to for from by over under up down off out back away around round through onto into across along before after while then than that which who whom whose is are was were has have had now still already again too also not off her him them it its his their this these those where when because so yet nor if unless until till like near behind beside between against about above below inside outside past pulled tugged tied undone open loose tight low high askew".split(" "));
const PART_WORDS = new Set("sleeve sleeves lapel lapels hem hems button buttons zip zipper seam seams lining tail tails strap straps buckle pocket pockets collar collars cuff cuffs fabric material label logo print pattern colour color shade brim visor peak crown band laces sole soles heel heels toe toes tongue strings string ribbon ribbons tassel tassels pleat pleats fold folds".split(" "));
/** True when the token right after an ambiguous head does not read as a noun the head modifies ("top shelf", "top brass", "boot inn", "chain link"). */
export function afterHeadOk(after: string): boolean {
  const m = /^\s+([A-Za-z][A-Za-z'-]*)/.exec(after); if (!m) return true;
  const w = m[1]; const lw = w.toLowerCase();
  if (/^[A-Z]/.test(w)) return false;
  if (AFTER_OK.has(lw) || PART_WORDS.has(lw) || FINITE_RE.test(lw) || CANON.has(lw.replace(/[- ]/g, "")) || CANON.has(lw.replace(/(?:es|s)$/, "")) || /(?:ing|ed|ly)$/.test(lw)) return true;
  return false;
}
/** "<head> of <non-material>": coat of varnish, veil of mist, chain of command, wedge of lemon. Materials/colours ("chain of gold") stay. */
export const PARTITIVE_RE = new RegExp(`^\\s+of\\s+(?!(?:the\\s+|pure\\s+|fine\\s+|finest\\s+|solid\\s+|real\\s+)?(?:${MOD_ALT}|pearls?|diamonds?|gold|silver|beads?|flowers?|marigolds?|jasmine|roses?|thorns?|shells?|coins?|keys?)(?:s|es)?${B1})[a-z]`, "i");

// ---------- sentences and lines ----------
const ABBR = /\b(INT|EXT|Mr|Mrs|Ms|Dr|Insp|Sgt|Lt|St|No|vs|Sc|a\.m|p\.m|etc)\./g;
export function sentences(par: string): { text: string; at: number }[] {
  const prot = par.replace(ABBR, (m) => m.replace(/\./g, " "));
  const out: { text: string; at: number }[] = []; let last = 0; let m: RegExpExecArray | null;
  const re = /(?<=[.!?])\s+(?=[A-Z"'(])/g;
  while ((m = re.exec(prot))) { out.push({ text: par.slice(last, m.index), at: last }); last = m.index + m[0].length; }
  out.push({ text: par.slice(last), at: last });
  return out.filter((x) => x.text.trim());
}
export const FINITE = "waits|sits|stands|walks|enters|exits|looks|turns|holds|carries|says|scans|arrives|smiles|nods|leans|pours|drinks|checks|watches|steps|comes|goes|stares|glances|sighs|laughs|freezes|pauses|stops|runs|moves|paces|frowns|grins|eats|sips|picks|takes|puts|pulls|opens|closes|is|has|hurries|strides|storms|climbs|kneels|crosses|rushes|follows|waves|lights|approaches|listens|speaks|shouts|whispers|reads|sets|drops|throws|pushes|grabs|lifts|rises|falls|fights|dances|reaches|stumbles|staggers|sprints|sprint|slumps|collapses|cries|screams|mutters|hesitates|shrugs|sees|hears|hugs|kisses|slaps|punches|points|bows|leaps|jumps|lies|sleeps|wakes|stretches|smokes|clutches|fiddles|twists|dabs|wipes|scrolls|answers|gets|makes|does|did|was|were|are|threads|lowers|wades|fusses|slip|inspects|receives|surge|sink|drives|emerges|spills|adjusts|raises|loosens|kicks|tightens|straightens|stirs|peels|changes|unhooks|drags|fight|hammers|tumble|backfires|showers|measures|rummages|dips|tears|knocks|blooms|line up|lines up|sweeps|marches|storms|chases|pulls|tries|imagines|fits|hands|gives|tosses|offers|blocks|passes|lends|shows|greets|slides|presents|serves|brings|fetches|lays|places|hangs|folds|tucks|packs|sends|leads|guides|joins|meets|calls|tells|asks|helps|notices|spots|ignores|shoves|drapes|wraps|ties|fastens|knots|buttons|zips|removes|strips|tears|rips|smears|throws|dumps|snaps|catches|burns|hurls|ushers|nudges|elbows|steers|escorts|carries";
export const FINITE_RE = new RegExp(`\\b(?:${FINITE})\\b`, "i");
export const SFX = new Set("BANG CRASH SLAM THUD CLICK BOOM SCREECH HONK RING BUZZ CU ECU POV INSERT ANGLE ON CLOSE ON WIDE TITLE SUPER CUT TO INTERCUT MONTAGE LATER CONTINUOUS BEAT SFX VFX CGI O.S. V.O. CONT'D THE END FADE INT EXT STUNT DOUBLE BODY DOUBLE".split(" "));
export const TITLE_WORDS = new Set(["inspector", "doctor", "mother", "father", "officer", "uncle", "aunt", "brother", "sister", "mrs", "miss", "nurse", "waiter", "guard", "boss", "constable", "sergeant", "captain", "colonel", "major", "judge", "professor", "sir", "madam", "master", "masterji", "saab", "sahib", "bhai", "didi", "editor", "pandit"]);
export const ROLE_RE = /\b(?:a|an|the)\s+((?:old |young |older |younger )?(?:waiter|waitress|nurse|doctor|guard|cop|constable|officer|soldier|steward|supervisor|receptionist|bouncer|priest|pandit|servant|maid|driver|clerk|man|woman|boy|girl|stranger|beggar|vendor|mechanic|policeman|sepoy|drunk|figure|stranger|passenger|editor))\b/gi;
export const FEMALE_HINT = /\b(mother|mrs|miss|ms|aunt|sister|wife|daughter|girl|woman|lady|queen|princess|nurse|bride|maid|widow|grandmother|amma|maa|didi|bhabhi|begum|rani|devi)\b/i;
export const MALE_HINT = /\b(father|mr|uncle|brother|husband|son|boy|man|king|prince|groom|grandfather|baba|papa|bhai|sahib|saab|raja|sir|inspector|constable|sergeant|captain|colonel|major|masterji|pandit)\b/i;

// ---------- hazards, crowds, events ----------
export type Conf = "HIGH" | "MEDIUM" | "LOW";
/** [family, trigger regex source, consequence, scope]. scene-scope notes are scene-wide (character null); subject-scope attach to the subject when known. */
export const HAZARDS: [string, string, string, "scene" | "subject"][] = [
  ["Rain/water", "rain (?:hammers|pours|lashes|soaks|drenches|falls|comes down|starts|batters|beats|streaks|sheets|drums)|in the rain|(?:pouring|heavy|driving|torrential|lashing) rain|it (?:is|was|starts|begins|keeps|has been) (?:still )?(?:raining|pouring|drizzling|snowing|hailing)|it rains|raining|rains (?:hard|heavily|steadily|down)|^rain\\.?$|downpour|drizzle|monsoon(?! palace)|thunderstorm|storm(?! (?:in a teacup|of (?:protest|applause|abuse|criticism)|drain|trooper))|hail(?!s? (?:of|a|the|from|down|him|her|them)\\b)|hailstorm|hailstones|snow(?:ing)?(?! (?:White|globe|leopard|plough|plow|cone|man|chains?|tyres?|tires?|patrol|report|day|queen))|blizzard|sleet|puddles?|water balloons?|hosepipe|bucket of water|sprinklers?", "wet costumes, duplicates, drying", "scene"],
  ["Water immersion", "(?:wades|swims|dives|jumps|falls|leaps|is pushed|is thrown|is shoved|gets pushed|plunges|dips|tumbles|slips) (?:in|into|under) (?:the |a )?(?:river|lake|sea|ocean|pool|water|waterfall|fountain|canal|well|tank|waves|swimming pool)|fully clothed|(?:climbs|crawls|drags (?:himself|herself)|hauls (?:himself|herself)|pulls (?:himself|herself)|scrambles|staggers|wades|is pulled|is dragged|is hauled) out of (?:the |a )?(?:river|lake|sea|ocean|pool|water|canal|well|tank|swimming pool|waves)|(?:emerges|surfaces|rises) from (?:the |a )?(?:river|lake|sea|ocean|pool|water|canal|well|tank|waves)", "duplicates, wet set, warm robe", "subject"],
  ["Shower/bath", "showers(?=[,.;!?]|\\s+(?:and|then|quickly|before|after|in the|at|first|off|down|for)\\b|$)|bathes(?=[,.;!?]|\\s+(?:and|then|quickly|before|after|in the|at|first)\\b|$)|steps out of the shower|takes a bath|in the shower|in the bath", "wet hair, towel or robe", "subject"],
  ["Fight/violence", "(?<!puts? up |put up |without a |spoiling for |itching for )(?:a|the|into a|in a|another|street|fist|bar|knife|pillow|water|mud) fight(?! (?:over|about|on|for) (?:the|a|an|his|her|their|it|this|that|money|custody|control|power|survival|justice|rights|budget|bill)\\b)|fight(?:s|ing)? (?:breaks out|erupts|back(?! (?:tears|a smile|a grin|a yawn|the urge|sleep|a laugh))|off (?:the|a|two|three|him|them|his|her)|with (?:the|a|him|her|them))|fights? (?:him|her|them)|they fight|fistfight|brawl|scuffle|(?:wrestles|tackles|grapples with) (?:him|her|them|me|us|(?:the|a|an) (?:man|woman|boy|girl|guy|kid|drunk|guard|cop|constable|thug|goon|stranger|attacker|bouncer|waiter|driver|officer|soldier|prisoner|suspect|other|first|second|nearest))|wrestles with (?:him|them|her(?=[,.;!?]|\\s+(?:and|to|on|in|for|until|before|as|but|then|over|across|down)\\b|$)|(?:the|a) (?:man|woman|guard|cop|thug|goon|attacker))|(?:punches|kicks|shoves|slaps|beats|thrashes|hits|headbutts|drags|throttles|strangles|stabs) (?:him|her|them|me|us|(?:the|a|an) (?:man|woman|boy|girl|guy|kid|drunk|guard|cop|constable|thug|goon|stranger|attacker|bouncer|waiter|driver|officer|soldier|prisoner|suspect|other|first|second|nearest))|thrown to the ground|is beaten|gets beaten|is stabbed|gets stabbed|stabbed|(?:pulls?|draws?|brandishes|wields|waves|raises|flashes|swings|presses|holds) (?:out )?(?:a|the|his|her) (?:knife|blade|dagger|gun|pistol|revolver)|knife (?:to|at|against|in) (?:his|her|their|the)|gunshot|gunfire|is shot|gets shot|shoots (?:him|her|them|at|the|a|into|through|twice|once)(?! a (?:look|glance|glare|smile|grin))|bullets? (?:fly|flies|rip|rips|tear|tears|hit|hits|whiz|whizz|graze|grazes|slam|slams|strike|strikes)|bullet wound|falls (?:to the (?:ground|floor)|into|off|down the)|tumbles (?:down|off|over|into)|is dragged|dragged (?:out|off|away|across|along|through|by|to|into|from)|car crash|crashes into|lathi charge|(?:a|the) riot(?! of)|riots?(?: break| erupt)", "tears, dirt, blood risk, duplicates", "subject"],
  ["Blood", "bleeds(?=[,.;!?]|\\s+(?:from|heavily|profusely|out|onto|all over|through|badly|freely|down|into his|into her)\\b|$)|bleeding(?! (?:heart|edge|money|cash))|blood (?:on|onto|runs|drips|blooms|soaks|spreads|pours|trickles|streams|seeps|spatters|splatters|sprays)|bloodied|blood-?stained|blood-?soaked|wound(?:ed|s)?(?!\\s+(?:up|down|tight(?:ly)?|round|around|the|a|his|her|it|its))", "duplicates, blood prep", "subject"],
  ["Fire/smoke", "on fire|catches fire|catches alight|sets? fire|set alight|flames|burning(?=\\s+(?:building|house|car|hut|room|bus|tent|barn|wreck|pyre|effigy|log|coals?|embers|tyres?|tires?|rubbish|garbage|papers?|torch(?:es)?|wood|timber|debris|down|around|nearby|fiercely|brightly|rubble|oil|ghee|hot|cloth|fabric|dupatta|saree|sari|shirt|sleeve))|(?:is|are|was|were|still|now) burning(?!\\s+(?:with|question|desire|ambition|need|up))|burns(?! (?:with|to know|out))|explosion|explodes(?! (?:with|in|at|into) )|(?:bomb|gas|the) blast|blast (?:rips|tears|throws|knocks|hits)|(?:thick|black|dense|acrid|billowing|choking|white|grey) smoke|smoke (?:fills|pours|billows|rises from the|chokes|engulfs|everywhere)|smoke-filled|through the smoke|clouds? of smoke|pyre", "FR duplicates, burnt breakdown", "subject"],
  ["Holi/colour", "holi|gulal|haldi|turmeric|colours? (?:thrown|flung|fly|flies)|drenched in colour|paint (?:splattered|thrown|flies)|pink colour", "colour-fast duplicates, everyone stained", "scene"],
  ["Mud/dirt", "(?:in|into|onto|through|covered in|caked in|fight in) (?:the )?mud|dust storm|covered in dust|oil-stained|(?<!elbow )grease(?! (?:monkey|pencil|gun|paint|the|his|her))|flour|cow dung", "breakdown, duplicates", "subject"],
  ["Food/drink", "food fight|pie fight|cake fight|eats(?! (?:at|away|into|up|out|(?:his|her|their|my|your) (?:words|heart|pride|hat)))|eating(?! (?:at|away|into|up))|tears into|digs into|devours|meal|dinner(?!\\s+(?:jacket|suit|dress))|lunch|breakfast|feast|buffet|plate of", "spill risk, spare tops", "scene"],
  ["Sweat", "sweat-soaked|drenched in sweat|soaked in sweat|sweating(?! bullets)|sweats(?=[,.;!?]|\\s+(?:profusely|heavily|freely|buckets|through|in the|under|visibly|and|as|despite|in)\\b|$)|sweat (?:pours|runs|drips|streams|trickles|beads|patches|stains|soaks|darkens)|sweat-?stained|sweat-?soaked|drips with sweat|wipes (?:the |away )?sweat|glistening with sweat|sweltering|scorching", "spare shirts", "subject"],
  ["Physical action", "sprints (?:across|down|up|through|towards?|after|away|to|for|off|out|into|along|back|past|over|round|around)|(?:breaks into a|at a|at full) sprint|chases (?:him|her|them|after|(?:the|a) (?:thief|man|boy|girl|kid|car|bus|train|dog|bike|jeep|van|truck|goons?|thugs?|suspect|pickpocket)|down the|through|across|along|up the)|chased (?:by|through|across|down|along|up|out)|gives chase|car chase|chase (?:scene|sequence)|climbs?(?:up |over |down |onto |through |into )?(?:the |a |an )?(?:wall|fence|tree|rope|ladder(?! of)|cliff|rocks?|hill|mountain|roof|scaffold(?:ing)?|drainpipe|pipe|gate|balcony|window|railing|rail|trellis|pillar|pole|mast|rigging|bank|slope|ridge|dune|rubble|tower|crane|bus|truck|lorry|train|tempo|tractor)|crawls|rolls (?:on|across|down) (?:the )?(?:ground|floor|grass|hill|slope|bank|stairs|steps|mud|dirt|sand|road|embankment|bed|carpet)|leaps (?:off|from|over|across|onto|down|through)|jumps (?:off|from|over|across|onto|down|through)|(?:rides?|riding|mounts?|astride|on|onto|off|from|revs?|kick-?starts?|straddles?) (?:a|the|his|her|their) (?:motorcycle|motorbike|scooter|bullet|bike)|motorcycle (?:chase|crash|stunt)|horse riding|on horseback", "movement fit, duplicates", "subject"],
  ["Dance", "(?<!(?:flames?|light|lights|shadows?|candle|fire|dust|leaves|smoke|eyes|reflections?|sunlight|words|numbers|curtains?|hair|motes|sparks|figures|thoughts)\\s+)dances?(?! (?:around|round) (?:the|a|an|his|her|it))|dancing|dance number|song sequence|item number|garba|sangeet", "sweat duplicates, movement fit", "scene"],
];
export const HAZARD_RES = HAZARDS.map(([, src]) => new RegExp(`${B0}(?:${src})${B1}`, "i"));
export const SUBS = "blood|mud|dust|sweat|paint|flour|oil|grease|soot|ash|rain|water|dirt|grime|colours?|gulal|haldi|turmeric|red wine|wine|coffee|tea|chai|milk|sauce|gravy|ketchup|cake|snow|sand|vomit|slime|foam|glitter|confetti|juice|curry|dal|beer|whisky|ice cream|ink";
export const hazardFamilyFor = (sub: string): number | null => (/blood/.test(sub) ? 4 : /colour|gulal|haldi|turmeric|paint/.test(sub) ? 6 : /water|rain|snow/.test(sub) ? 0 : /mud|dust|dirt|grime|sand|oil|grease|soot|ash|flour/.test(sub) ? 7 : null);
export const PARTS = "sleeves?|collar|cuffs?|front|chest|lap|back|shoulders?|hem|pallu|trousers|skirt|dress|shirt|blouse|kurta|jacket|saree|sari|coat";
/** After a garment/part head in a stain pattern, these mean the head was a set-dressing noun ("back seat", "front page"). */
export const NOT_PART_AFTER = "(?!\\s+(?:seats?|pages?|doors?|walls?|steps?|rows?|yard|garden|porch|windows?|cover|bumper|wheel|tyre|tire|lawn|room|desk|gate|entrance|exit|of the (?:car|house|room|bus|van|jeep|truck|shop|building)))";
export const OWNER = "his|her|their|the|[A-Z][A-Za-z'-]*(?: [A-Z][A-Za-z'-]*)?'s";
export const BLOOD_RE = new RegExp(`\\b(?:blood|bleeds?|bleeding)\\b[^.;]{0,40}?\\b(?:on|onto|down|across|over|into|through)\\s+(${OWNER})\\s+((?:(?:${MOD_ALT})\\s+)*(?:${HEAD_ALT}|${PARTS}))${B1}${NOT_PART_AFTER}`, "gi");
export const STAIN_RE = new RegExp(`\\b(${SUBS})\\s+stains?\\s+(?:on|down|across)\\s+(${OWNER})\\s+((?:(?:${MOD_ALT})\\s+)*(?:${HEAD_ALT}|${PARTS}))${B1}${NOT_PART_AFTER}`, "gi");
export const SPILL_RE = new RegExp(`\\b(?:spills?|pours?|splashes|dumps|throws|flings|knocks over|tips)\\b[^.]{0,40}?\\b(${SUBS})\\b[^.]{0,40}?\\b(?:on|onto|down|across|over|all over|into)\\s+(${OWNER})\\s+((?:(?:${MOD_ALT})\\s+)*(?:${HEAD_ALT}|${PARTS}))${B1}`, "gi");
export const COVERED_RE = new RegExp(`\\b(covered|caked|spattered|splattered|smeared|streaked|dripping|plastered|dusted|splashed|doused|drenched|soaked)\\s+(?:in|with)\\s+((?:pink|red|green|yellow|blue|white|wet|fresh|dried|thick)\\s+)?(${SUBS})\\b`, "gi");
export const BODY_CTX_RE = /^\s+(in hand|over (?:his|her|their|one) shoulder|under (?:his|her|their) arm|(?:on|onto|from|off) (?:his|her|their|[A-Z][A-Za-z'-]*(?: [A-Z][A-Za-z'-]*)?'s) (?:wrist|finger|neck|head|feet|foot|hip|ears?|nose|hair|forehead|ankle|waist|shoulders?|hands?|arms?|chest|torso|back)|(?:around|round|across) (?:his|her|their|[A-Z][A-Za-z'-]*(?: [A-Z][A-Za-z'-]*)?'s) (?:neck|wrist|waist|shoulders?|chest|torso|body|head|hips|arm|ankle|forehead|hair)|up to (?:his|her) (?:elbows|wrists))\b/i;
/** Recipient of a placed/draped/handed garment: "<verb> a shawl over Priya", "on Raj's head", "around her shoulders". */
export const RECIPIENT_TAIL_RE = /^\s+(?:over|around|round|onto|on|across|to|over to|across to|back to)\s+([A-Z][A-Za-z'-]*(?: [A-Z][A-Za-z'-]*)?(?:'s)?|him|her|them)\b/;
export const HANDOVER_RE = /\b(?:hands|handed|handing|gives|gave|giving|passes|passed|passing|tosses|tossed|tossing|offers|offered|offering|throws|threw|throwing|lends|lent|lending|brings|brought|bringing|fetches|fetching|holds out|holding out|slides|sliding)\s+(?:back\s+)?([A-Z][A-Za-z'-]*(?: [A-Z][A-Za-z'-]*)?|him|her|them)\s*$/;
export const HANDOVER_VERB_RE = /\b(?:hands|handed|handing|gives|gave|giving|passes|passed|passing|tosses|tossed|tossing|offers|offered|offering|throws|threw|throwing|lends|lent|lending|brings|brought|bringing|fetches|fetching|holds out|holding out|slides|sliding)\b[^.;]*$/i;
const CROWD = "constables|cops|police(?:men)?|officers|soldiers|sepoys|troops|guards|nurses|doctors|orderlies|waiters|servers|bouncers|staff|students|schoolchildren|children|villagers|passengers|commuters|guests|wedding guests|baraatis|mourners|protest(?:e|o)rs|dancers|musicians|band|extras|crowd|throng|mob|onlookers|labourers|workers|farmers|fishermen|monks|priests|pandits|bridesmaids|groomsmen|prisoners|inmates|men|women|people|rioters|policewomen";
const COUNT = "\\d{1,4}|three|four|five|six|seven|eight|nine|ten|eleven|twelve|fifteen|twenty|thirty|forty|fifty|sixty|(?:a|one|two|three|four|five) hundred|hundreds of|a dozen|dozens of|scores of|a handful of|a group of|a crowd of|a sea of|a line of|a row of|several|a few";
const LOOK = `((?:(?:${MOD_ALT})\\s+){0,2}(?:${HEAD_ALT}(?:es|s)?|(?:khaki|white|black|saffron)(?!\\s+(?:vans?|cars?|jeeps?|trucks?|bus(?:es)?|houses?|rooms?|paint|walls?|tents?|flags?|light|noise|smoke|dust|sheets?|coats of))|wedding finery|finery|formation|livery)(?:\\s+and\\s+(?:(?:${MOD_ALT})\\s+)?(?:${HEAD_ALT})(?:es|s)?)?)`;
export const COUNTED_RE = new RegExp(`\\b(${COUNT})\\s+(?:(?:wedding|young|old|armed|angry|uniformed|drunken)\\s+)?(${CROWD})\\b(?:\\s+in\\s+${LOOK})?`, "gi");
export const UNI_RE = new RegExp(`\\b(${CROWD})\\s+in\\s+${LOOK}`, "gi");
export const COLLECTIVE_RE = new RegExp(`\\b(crowd|mob|throng|procession|baraat)(?!\\s*-|\\s+(?:funding|pleaser|pleasing|sourcing|sourced|control|noise|favourite|favorite|puller|scene shot|mentality|rule|boss))(?:\\s+of\\s+(${CROWD}|\\w+))?\\b`, "i");
export const EVENT_RE = /(?<!\b(?:hotel|phone|mobile|no|poor|bad|signal|prior|previous|other|from the|after the|since the|before the|vacuums the|hoovers the|cleans the|rolls up the)\s+)\b(wedding(?!\s+(?:ring|band|dress|photo|album|planner|guests?|cake|bakery|shop|card|invitation|invite|season|magazine|website|anniversary|lehenga|saree|sari|finery|outfit|suit|sherwani|jewellery|jewelry))|sangeet|mehendi ceremony|haldi ceremony|mandap|pheras|reception(?!\s*(?:desk|area|counter|room|ist))|engagement(?!\s+(?:ring|letter|s)|s)|funeral|cremation|diwali|holi|eid|garba|navratri|gala(?!\s+(?:theatre|theater|cinema|apple))|red carpet(?!\s+(?:cleaner|stain))|fancy dress|masquerade)\b/i;
/** In a slugline only unmistakable event locations count. */
export const SLUG_EVENT_RE = /\b(WEDDING(?!\s+(?:CAKE|BAKERY|SHOP|CARD|PLANNER|DRESS|PHOTO|ALBUM|MAGAZINE|WEBSITE))|WEDDING RECEPTION|RECEPTION (?:HALL|VENUE|PARTY|DINNER)|SANGEET|MEHENDI|HALDI|MANDAP|PHERAS|ENGAGEMENT (?:PARTY|CEREMONY|HALL|VENUE)|FUNERAL|CREMATION|DIWALI|HOLI|EID|GARBA|NAVRATRI|GALA (?:DINNER|NIGHT|BALL|EVENT|HALL)|RED CARPET|FANCY DRESS|MASQUERADE)\b/;
/** Weather in the time/weather tail of a slugline ("EXT. STREET - NIGHT - RAIN", "(RAINING)"). */
export const SLUG_WEATHER_RE = /\b(RAIN(?:ING|Y|STORM)?|STORM(?:Y)?|SNOW(?:ING)?|MONSOON|DOWNPOUR|THUNDERSTORM|DRIZZLE|HAIL|BLIZZARD|SLEET)\b/;
export const LOCATION_RE = /\b(tailor|boutique|dressing room|laundry(?!\s+(?:room|basket|bag|pile|day|chute|cupboard|hamper))|dhobi|wardrobe|shoe store|costume)\b/i;
export const SLUG_TIME = /\b(CONTINUOUS|SAME TIME|SAME|MOMENTS LATER|LATER|MEANWHILE|INTERCUT|FLASHBACK|FLASH ?FORWARD|DREAM(?: SEQUENCE)?|MEMORY|MONTAGE|PRESENT DAY|DAY (?:\d+|TWO|THREE|FOUR|FIVE)|(?:\d+|\w+) (?:YEARS?|MONTHS?|WEEKS?|DAYS?|HOURS?) (?:EARLIER|LATER|AGO)|THE NEXT (?:MORNING|DAY)|THAT NIGHT)\b/;
export const TIME_CARD = /^(?:(?:TITLE|SUPER|SUPERIMPOSE|CARD):\s*.+|LATER|MOMENTS LATER|CONTINUOUS|THE NEXT (?:MORNING|DAY)|THAT NIGHT|[A-Z ,'-]+ (?:LATER|EARLIER|AGO)|(?:19|20)\d{2}|(?:FLASHBACK|FLASH ?FORWARD|DREAM SEQUENCE|MONTAGE|INTERCUT|PRESENT DAY)(?: TO)?|(?:BACK TO|RETURN TO) (?:THE )?(?:PRESENT|SCENE|PRESENT DAY|REALITY)|END (?:OF )?(?:FLASHBACK|DREAM|MONTAGE))[:.]?$/;
/** Standalone transition lines that end in a colon and would otherwise be parsed as a character cue. */
export const TRANSITION_RE = /^(FLASHBACK|FLASH ?FORWARD|DREAM SEQUENCE|MONTAGE|INTERCUT|PRESENT DAY|BACK TO (?:THE )?(?:PRESENT|SCENE|PRESENT DAY|REALITY)|END (?:OF )?(?:FLASHBACK|DREAM|MONTAGE))(?: TO)?[:.]?$/;
/** Violence verb directly before a character name: "shoves Raj", "punches Dev" (checked in code, since names are case-sensitive). */
export const VIOLENCE_BEFORE_NAME_RE = /\b(fights?|punches|kicks|shoves|slaps|beats|thrashes|hits|headbutts|drags|throttles|strangles|stabs|shoots|tackles|wrestles|attacks|grabs and (?:punches|hits))\s+$/i;
export const AGE_TEXT = (w: string) => (/^younger$/i.test(w) ? "Younger: de-ageing / younger look, period-appropriate wardrobe" : "Older: ageing make-up, aged wardrobe");
export const PERIOD_RE = /\b((?:1[89]|20)\d{2}|(?:19)?[2-9]0s|the (?:twenties|thirties|forties|fifties|sixties|seventies|eighties|nineties)|British Raj|colonial|Mughal|Rajput era|partition|sepoy|nawab|zamindar|freedom fighter)\b/;
