import { useMemo } from "react";
import { Link, useSearchParams } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { Printer } from "lucide-react";
import { api, p } from "@/api/client";
import { useProject } from "@/state/project";
import { fmtDateLong, humanize, todayISO } from "@/lib/format";
import { Card, Empty, Input, PageHead, Spinner } from "@/components/ui";

interface SidesScene { id: string; number: string; name?: string | null; location?: string | null; intExt?: string | null; timeOfDay?: string | null; scriptDay?: string | null; pages?: string | null; revision?: string | null; status: string; hasScript: boolean; text: string; characters: { id: string; name: string; castNumber?: number | null; change?: string | null }[] }
interface Sides { project: { name: string; code: string; shootingDay: number }; generatedBy: string; generatedAt: string; scenes: SidesScene[] }

/** Render stored scene text in screenplay layout: slugline, action, character cues, dialogue, parentheticals. */
function ScriptBlock({ text }: { text: string }) {
  const lines = text.split("\n");
  return (
    <div className="script">
      {lines.map((raw, i) => {
        const line = raw.replace(/\s+$/, "");
        if (!line.trim()) return <div key={i} className="s-blank" />;
        if (i === 0) return <div key={i} className="s-slug">{line}</div>;
        if (/^[A-Z0-9][A-Z0-9 .'#&\-]*:$/.test(line.trim())) return <div key={i} className="s-cue">{line.trim().replace(/:$/, "")}</div>;
        if (/^\s{2,}/.test(raw)) {
          const t = line.trim();
          return <div key={i} className={/^\(.*\)$/.test(t) ? "s-paren" : "s-dialogue"}>{t}</div>;
        }
        return <div key={i} className="s-action">{line}</div>;
      })}
    </div>
  );
}

export default function Sides() {
  const { projectId } = useProject();
  const [sp, setSp] = useSearchParams();
  const ids = sp.get("ids") || "";
  const date = sp.get("date") || (ids ? "" : todayISO());
  const qs = ids ? `ids=${ids}` : `date=${date}`;
  const { data, isLoading } = useQuery({ queryKey: ["sides", projectId, qs], queryFn: () => api<Sides>(p(projectId, `/scenes/sides?${qs}`)) });
  const total = useMemo(() => (data?.scenes || []).reduce((n, s) => n + eighths(s.pages), 0), [data]);
  const base = `/p/${projectId}`;
  return (
    <div>
      <style>{`
        .script { font-family: "Courier New", Courier, monospace; font-size: 12pt; line-height: 1.25; max-width: 62ch; }
        .s-slug { font-weight: 700; text-transform: uppercase; margin: 16px 0 8px; }
        .s-action { margin: 0 0 8px; white-space: pre-wrap; }
        .s-cue { text-transform: uppercase; margin: 8px 0 0 22ch; }
        .s-dialogue { margin: 0 12ch 0 12ch; }
        .s-paren { margin: 0 0 0 17ch; font-style: italic; }
        .s-blank { height: 6px; }
        .sides-scene { break-inside: avoid-page; page-break-inside: avoid; position: relative; }
        .sides-scene + .sides-scene { margin-top: 28px; padding-top: 20px; border-top: 1px dashed var(--border); }
        .watermark { position: fixed; inset: 0; display: grid; place-items: center; pointer-events: none; z-index: 0; }
        .watermark span { font-family: var(--font); font-size: 42px; font-weight: 800; color: rgba(20,21,26,0.06); transform: rotate(-28deg); white-space: nowrap; letter-spacing: 0.04em; }
        @media print { .watermark span { color: rgba(0,0,0,0.08); } .sides-cover { page-break-after: always; } .card { border: none; padding: 0; } }
      `}</style>
      <div className="no-print">
        <PageHead title="Sides" sub="Script pages for a shoot day, from the uploaded screenplay. Watermarked with your name and the date." crumbs={<><Link to={`${base}/scenes`}>Scenes</Link> / Sides</>}
          actions={<><Input type="date" value={date} onChange={(e) => setSp({ date: e.target.value }, { replace: true })} style={{ width: "auto" }} /><button className="btn btn-primary" disabled={!data?.scenes.length} onClick={() => window.print()}><Printer size={16} /> Print</button></>} />
      </div>
      {isLoading || !data ? <Spinner /> : data.scenes.length === 0 ? <Card><Empty icon="📄" title="No scenes for this date" hint="Set shoot dates on scenes, or open sides from a scene list selection." /></Card> : (
        <>
          <div className="watermark" aria-hidden><span>{data.generatedBy} · {fmtDateLong(data.generatedAt)}</span></div>
          <Card className="sides-cover mb-2">
            <div className="eyebrow subtle">Sides · {data.project.name} ({data.project.code}) · Shooting day {data.project.shootingDay}</div>
            <h2 className="mt-1">{date ? fmtDateLong(date) : `${data.scenes.length} scenes`}</h2>
            <div className="subtle">{data.scenes.length} scene{data.scenes.length === 1 ? "" : "s"} · {formatEighths(total)} pages · generated by {data.generatedBy}</div>
            <div className="table-wrap mt-2"><table className="table">
              <thead><tr><th>Sc</th><th>Slugline</th><th>Story day</th><th>Pages</th><th>Cast</th><th>Rev.</th></tr></thead>
              <tbody>{data.scenes.map((s) => <tr key={s.id}><td className="mono bold">{s.number}</td><td>{[s.intExt, s.location, s.timeOfDay ? humanize(s.timeOfDay) : null].filter(Boolean).join(". ") || s.name}{s.status === "OMITTED" ? " (OMITTED)" : ""}</td><td>{s.scriptDay || "—"}</td><td className="mono">{s.pages || "—"}</td><td>{s.characters.map((c) => `${c.castNumber != null ? c.castNumber + ". " : ""}${c.name}${c.change ? ` (${c.change})` : ""}`).join(", ") || "—"}</td><td className="subtle">{s.revision || "—"}</td></tr>)}</tbody>
            </table></div>
          </Card>
          <Card>
            {data.scenes.map((s) => (
              <div key={s.id} className="sides-scene">
                <div className="row between wrap subtle small no-print"><span>Sc {s.number}{s.revision ? ` · ${s.revision}` : ""}</span><Link to={`${base}/scenes/${s.id}`}>Open scene</Link></div>
                {s.hasScript ? <ScriptBlock text={s.text} /> : <div className="script"><div className="s-slug">{s.number} {[s.intExt, s.location, s.timeOfDay].filter(Boolean).join(". ")}</div><div className="s-action subtle">No script text for this scene (added by hand). Upload the screenplay to include its pages.</div></div>}
              </div>
            ))}
          </Card>
        </>
      )}
    </div>
  );
}

function eighths(pages?: string | null): number {
  if (!pages) return 0;
  const m = /^(?:(\d+)\s*)?(?:(\d)\/8)?$/.exec(pages.trim());
  if (!m) return 0;
  return (Number(m[1] || 0) * 8) + Number(m[2] || 0);
}
function formatEighths(e: number): string {
  const whole = Math.floor(e / 8);
  const rem = e % 8;
  return whole && rem ? `${whole} ${rem}/8` : whole ? String(whole) : rem ? `${rem}/8` : "0";
}
